--This table stores the internal names of settlements and their respective assigned ancillaries, along with filepaths for the associated .tga
--The format is as follows: ["factionName"] = {["settlement"] = {anc = "ancName", tga = "tgaPath"}} 

ancTable = {
    ["byzantium"] = {["Constantinople"] = {anc = "kephalatikeuon_of_constantinople", tga = "kephalatikeuon_of_constantinople.tga"},["Christoupolis"] = {anc = "kephale_of_christoupolis", tga = "cross_red_coa.tga"},
            ["Adrianople"] = {anc = "kephale_of_hadrianoupolis", tga = "kephale_of_hadrianoupolis.tga"},["Raidestos"] = {anc = "kephale_of_raidestos", tga = "cross_red_coa.tga"}, 
            ["Kallipolis"] = {anc = "kephale_of_kallipolis", tga = "cross_red_coa.tga"}, ["Didymoteichon"] = {anc = "kephale_of_didymoteichon", tga = "cross_red_coa.tga"},
            ["Galata"] = {anc = "kephale_of_pera", tga = "kephale_of_pera.tga"}, ["Serrai"] = {anc = "despot_of_serres", tga = "despot_of_serres.tga"},
            ["Salonica"] = {anc = "despot_of_thessalonica", tga = "despot_of_thessalonica.tga"}, ["Berroia"] = {anc = "kephale_of_berroia", tga = "kephale_of_berroia.tga"},
            ["Kastoria"] = {anc = "kephale_of_kastoria", tga = "kephale_of_kastoria.tga"}, ["Kruje"] = {anc = "kephale_of_lissos", tga = "lord_of_mat.tga"},
            ["Valona"] = {anc = "despot_of_valona", tga = "despot_of_valona.tga"}, ["Modon"] = {anc = "kephale_of_modon", tga = "kephale_of_modon.tga"},
            ["Lepanto"] = {anc = "despot_of_angelokastron", tga = "despot_of_angelokastron.tga"}, ["Larissa"] = {anc = "kephale_of_great_vlachia", tga = "kephale_of_great_vlachia.tga"}, 
            ["Neopatria"] = {anc = "sebastokrator_of_thessaly", tga = "sebastokrator_of_thessaly.tga"}, ["Athens"] = {anc = "kephale_of_athinai", tga = "kephale_of_athinai.tga"}, 
            ["Corinth"] = {anc = "kephale_of_corinth", tga = "kepahle_of_corinth.tga"}, ["Patras"] = {anc = "kephale_of_patras", tga = "kephale_of_patras.tga"}, 
            ["Andreville"] = {anc = "kephale_of_andravida", tga = "kephale_of_andravida.tga"}, ["Pozega"] = {anc = "zhupan_of_pozega", tga = "zhupan_of_pozega.tga"}, 
            ["Bihac"] = {anc = "knez_of_bihac", tga = "knez_of_bihac.tg"}, ["Knin"] = {anc = "knez_of_knin", tga = "knez_of_knin.tga"},
            ["Zadar"] = {anc = "kephale_of_iadera", tga = "knez_of_zadar.tga"}, ["Split"] = {anc = "dux_of_spalatum", tga = "dux_of_spalatum.tga"},
            ["Ston"] = {anc = "kephale_of_ston", tga = "knez_of_ston.tga"}, ["Ragusa"] = {anc = "dux_of_ragusa", tga = "rector_of_ragusa.tga"},
            ["Blagaj"] = {anc = "grand_voivode_of_hum", tga = "grand_voivode_of_hum.tga"}, ["Jajce"] = {anc = "", tga = ""},
            ["Doboj"] = {anc = "", tga = ""}, ["Srebrenik"] = {anc = "", tga = ""},
            ["Bobovac"] = {anc = "", tga = ""}, ["Kotor"] = {anc = "", tga = ""},
            ["Skadar"] = {anc = "", tga = ""}, ["Uzice"] = {anc = "", tga = ""},
            ["Ras"] = {anc = "", tga = ""}, ["Prizren"] = {anc = "", tga = ""},
            ["Novo_Brdo"] = {anc = "", tga = ""}, ["Nis"] = {anc = "", tga = ""},
            ["Skopje"] = {anc = "", tga = ""}, ["Ohrid"] = {anc = "", tga = ""},
            ["Prilep"] = {anc = "", tga = ""}, ["Stip"] = {anc = "", tga = ""},
            ["Rudnik"] = {anc = "", tga = ""}, ["Branicevo"] = {anc = "", tga = ""},
            ["Nandorfehervar"] = {anc = "", tga = ""}, ["Bdin"] = {anc = "", tga = ""},
            ["Sredets"] = {anc = "", tga = ""}, ["Tsepina"] = {anc = "", tga = ""},
            ["Plovdiv"] = {anc = "", tga = ""}, ["Lovets"] = {anc = "", tga = ""},
            ["Nikopol"] = {anc = "kephale_of_nikopolis", tga = "cross_red_coa.tga"}, ["Tarnovo"] = {anc = "", tga = ""},
            ["Drastar"] = {anc = "", tga = ""}, ["Karvuna"] = {anc = "", tga = ""},
            ["Varna"] = {anc = "", tga = ""}, ["Nesebar"] = {anc = "", tga = ""},
            ["Buda"] = {anc = "", tga = ""}, ["Pest"] = {anc = "", tga = ""},
            ["Pozsony"] = {anc = "", tga = ""}, ["Veszprem"] = {anc = "", tga = ""},
            ["Pecs"] = {anc = "", tga = ""}, ["Ujlak"] = {anc = "", tga = ""},
            ["Temesvar"] = {anc = "", tga = ""}, ["Varad"] = {anc = "", tga = ""},
            ["Debrecen"] = {anc = "", tga = ""}, ["Kassa"] = {anc = "", tga = ""},
            ["Beszterce"] = {anc = "", tga = ""}, ["Gyulafehervar"] = {anc = "", tga = ""},
            ["Fagaras"] = {anc = "", tga = ""}, ["Kronstadt"] = {anc = "", tga = ""},
            ["Severin"] = {anc = "", tga = ""}, ["Craiova"] = {anc = "", tga = ""},
            ["Arges"] = {anc = "", tga = ""}, ["Targoviste"] = {anc = "", tga = ""},
            ["Giurgiu"] = {anc = "", tga = ""}, ["Braila"] = {anc = "", tga = ""},
            ["Iasi"] = {anc = "", tga = ""}, ["Targu_Neamt"] = {anc = "", tga = ""},
            ["Suceava"] = {anc = "", tga = ""}, ["Hotin"] = {anc = "", tga = ""},
            ["Halicz"] = {anc = "", tga = ""}, ["Kamianets"] = {anc = "", tga = ""},
            ["Bratzlav"] = {anc = "", tga = ""}, ["Ozu-Cale"] = {anc = "", tga = ""},
            ["Oleski"] = {anc = "", tga = ""}, ["Qirim"] = {anc = "", tga = ""},
            ["Caffa"] = {anc = "", tga = ""}, ["Theodoro"] = {anc = "", tga = ""},
            ["Pola"] = {anc = "", tga = ""}, ["Udine"] = {anc = "", tga = ""},
            ["Treviso"] = {anc = "", tga = ""}, ["Venezia"] = {anc = "", tga = ""},
            ["Padova"] = {anc = "", tga = ""}, ["Verona"] = {anc = "", tga = ""},
            ["Brescia"] = {anc = "", tga = ""}, ["Como"] = {anc = "", tga = ""},
            ["Milan"] = {anc = "", tga = ""}, ["Asti"] = {anc = "", tga = ""},
            ["Genova"] = {anc = "", tga = ""}, ["Parma"] = {anc = "", tga = ""},
            ["Modena"] = {anc = "", tga = ""}, ["Ferrara"] = {anc = "", tga = ""},
            ["Ravenna"] = {anc = "", tga = ""}, ["Bologna"] = {anc = "", tga = ""},
            ["Firenze"] = {anc = "", tga = ""}, ["Lucca"] = {anc = "", tga = ""},
            ["Pisa"] = {anc = "", tga = ""}, ["Siena"] = {anc = "", tga = ""},
            ["Arezzo"] = {anc = "", tga = ""}, ["Urbino"] = {anc = "", tga = ""},
            ["Ancona"] = {anc = "", tga = ""}, ["Perugia"] = {anc = "", tga = ""},
            ["Spoleto"] = {anc = "", tga = ""}, ["Rome_Province"] = {anc = "", tga = ""},
            ["Rome"] = {anc = "", tga = ""}, ["Aquila"] = {anc = "", tga = ""},
            ["Napoli"] = {anc = "", tga = ""}, ["Salerno"] = {anc = "", tga = ""},
            ["San_Severo"] = {anc = "giustiziaro_of_capitanata", tga = "giustiziaro_of_capitanata.tga"}, ["Bari"] = {anc = "giustiziaro_of_bari", tga = "giustiziaro_of_bari.tga"},
            ["Taranto"] = {anc = "prince_of_taranto", tga = "prince_of_taranto.tga"}, ["Lecce"] = {anc = "", tga = ""},
            ["Potenza"] = {anc = "", tga = ""}, ["Cosenza"] = {anc = "", tga = ""},
            ["Gorz"] = {anc = "", tga = ""}, ["Laibach"] = {anc = "", tga = ""},
            ["Cilli"] = {anc = "", tga = ""}, ["Sankt_Veit"] = {anc = "", tga = ""},
            ["Gratz"] = {anc = "", tga = ""}, ["Wien"] = {anc = "", tga = ""},
            ["Linz"] = {anc = "", tga = ""}, ["Salzburg"] = {anc = "", tga = ""},
            ["Innsbruck"] = {anc = "", tga = ""}, ["Trient"] = {anc = "", tga = ""},
            ["Chur"] = {anc = "", tga = ""}, ["Zurich"] = {anc = "", tga = ""},
            ["Luzern"] = {anc = "", tga = ""}, ["Bern"] = {anc = "", tga = ""},
            ["Brunn"] = {anc = "", tga = ""}, ["Ceske_Budejovice"] = {anc = "", tga = ""},
            ["Straubing"] = {anc = "", tga = ""}, ["Munchen"] = {anc = "", tga = ""},
            ["Ingolstadt"] = {anc = "", tga = ""}, ["Augsburg"] = {anc = "", tga = ""},
            ["Konstanz"] = {anc = "", tga = ""}, ["Freiburg"] = {anc = "", tga = ""},
            ["Stuttgart"] = {anc = "", tga = ""}, ["Strassburg"] = {anc = "", tga = ""},
            ["Uskudar"] = {anc = "", tga = ""}, ["Iznikmid"] = {anc = "", tga = ""},
            ["Iznik"] = {anc = "", tga = ""}, ["Eskisehir"] = {anc = "", tga = ""},
            ["Bursa"] = {anc = "", tga = ""}, ["Balik_Hisar"] = {anc = "", tga = ""},
            ["Pegai"] = {anc = "", tga = ""}, ["Bergama"] = {anc = "", tga = ""},
            ["Manisa"] = {anc = "", tga = ""}, ["Smyrna"] = {anc = "", tga = ""},
            ["Guzelhisar"] = {anc = "", tga = ""}, ["Milas"] = {anc = "", tga = ""},
            ["Beskaza"] = {anc = "", tga = ""}, ["Adalia"] = {anc = "", tga = ""},
            ["Alaiye"] = {anc = "", tga = ""}, ["Karaman"] = {anc = "", tga = ""},
            ["Philadelphia"] = {anc = "kephale_of_philadelphia", tga = "chi_rho_black.tga"}, ["Ladik"] = {anc = "", tga = ""},
            ["Burdur"] = {anc = "", tga = ""}, ["Aksehir"] = {anc = "", tga = ""},
            ["Konya"] = {anc = "", tga = ""}, ["Usak"] = {anc = "", tga = ""},
            ["Kutahya"] = {anc = "", tga = ""}, ["Kara_Hissar"] = {anc = "", tga = ""},
            ["Angora"] = {anc = "kephale_of_ankyra", tga = "cross_red_coa.tga"}, ["Kangri"] = {anc = "", tga = ""},
            ["Bolu"] = {anc = "", tga = ""}, ["Amastri"] = {anc = "", tga = ""},
            ["Kastamonu"] = {anc = "", tga = ""}, ["Corfu"] = {anc = "kephale_of_corfu", tga = "chi_rho_circle.tga"},
            ["Candia"] = {anc = "kephale_of_chandax", tga = "cross_red_coa.tga"}, ["Rhodes"] = {anc = "", tga = ""},
            ["Kos"] = {anc = "kephale_of_kos", tga = "cross_red_coa.tga"}, ["Nasso"] = {anc = "kephale_of_cyclades", tga = "cross_red_coa.tga"},
            ["Negroponte"] = {anc = "kephale_of_euboea", tga = "chi_rho_circle.tga"}, ["Chio"] = {anc = "kephale_of_chios", tga = "kephale_of_chios.tga"},
            ["Mytilene"] = {anc = "", tga = ""}, ["Palaiokastro"] = {anc = "", tga = ""},
            ["Nicosie"] = {anc = "doux_of_kyprou", tga = "doux_of_kyprou.tga"}, ["Messina"] = {anc = "kephale_of_messina", tga = "kephale_of_messina.tga"},
            ["Palermo"] = {anc = "kephale_of_palermo", tga = "kephale_of_palermo.tga"}, ["Siracusa"] = {anc = "kephale_of_siracusa", tga = "chi_rho_circle.tga"},
            ["Cagliari"] = {anc = "archon_of_sardinia", tga = "chi_rho_circle.tga"}},
            
    ["hungary"] = {["Pozega"] = {anc = "", tga = ""}, ["Zagreb"] = {anc = "", tga = ""},
            ["Bihac"] = {anc = "", tga = ""}, ["Knin"] = {anc = "", tga = ""},
            ["Zadar"] = {anc = "", tga = ""}, ["Split"] = {anc = "", tga = ""},
            ["Ston"] = {anc = "", tga = ""}, ["Ragusa"] = {anc = "", tga = ""},
            ["Blagaj"] = {anc = "", tga = ""}, ["Jajce"] = {anc = "", tga = ""},
            ["Doboj"] = {anc = "", tga = ""}, ["Srebrenik"] = {anc = "", tga = ""},
            ["Bobovac"] = {anc = "", tga = ""}, ["Kotor"] = {anc = "", tga = ""},
            ["Skadar"] = {anc = "", tga = ""}, ["Uzice"] = {anc = "", tga = ""},
            ["Ras"] = {anc = "", tga = ""}, ["Prizren"] = {anc = "", tga = ""},
            ["Novo_Brdo"] = {anc = "", tga = ""}, ["Nis"] = {anc = "", tga = ""},
            ["Skopje"] = {anc = "", tga = ""}, ["Ohrid"] = {anc = "", tga = ""},
            ["Prilep"] = {anc = "", tga = ""}, ["Stip"] = {anc = "", tga = ""},
            ["Rudnik"] = {anc = "", tga = ""}, ["Branicevo"] = {anc = "", tga = ""},
            ["Nandorfehervar"] = {anc = "", tga = ""}, ["Bdin"] = {anc = "", tga = ""},
            ["Sredets"] = {anc = "", tga = ""}, ["Tsepina"] = {anc = "", tga = ""},
            ["Plovdiv"] = {anc = "", tga = ""}, ["Lovets"] = {anc = "", tga = ""},
            ["Nikopol"] = {anc = "", tga = ""}, ["Tarnovo"] = {anc = "", tga = ""},
            ["Drastar"] = {anc = "", tga = ""}, ["Karvuna"] = {anc = "", tga = ""},
            ["Varna"] = {anc = "", tga = ""}, ["Nesebar"] = {anc = "", tga = ""},
            ["Galata"] = {anc = "", tga = ""}, ["Constantinople"] = {anc = "", tga = ""},
            ["Raidestos"] = {anc = "", tga = ""}, ["Kallipolis"] = {anc = "", tga = ""},
            ["Didymoteichon"] = {anc = "", tga = ""}, ["Adrianople"] = {anc = "", tga = ""},
            ["Christoupolis"] = {anc = "", tga = ""}, ["Serrai"] = {anc = "", tga = ""},
            ["Salonica"] = {anc = "", tga = ""}, ["Berroia"] = {anc = "", tga = ""},
            ["Kastoria"] = {anc = "", tga = ""}, ["Kruje"] = {anc = "", tga = ""},
            ["Durazzo"] = {anc = "", tga = ""}, ["Valona"] = {anc = "", tga = ""},
            ["Ioannina"] = {anc = "", tga = ""}, ["Lepanto"] = {anc = "", tga = ""},
            ["Larissa"] = {anc = "", tga = ""}, ["Neopatria"] = {anc = "", tga = ""},
            ["Athens"] = {anc = "", tga = ""}, ["Corinth"] = {anc = "", tga = ""},
            ["Patras"] = {anc = "", tga = ""}, ["Andreville"] = {anc = "", tga = ""},
            ["Modon"] = {anc = "", tga = ""}, ["Mystras"] = {anc = "", tga = ""},
            ["Buda"] = {anc = "", tga = ""}, ["Pest"] = {anc = "", tga = ""},
            ["Pozsony"] = {anc = "", tga = ""}, ["Veszprem"] = {anc = "", tga = ""},
            ["Pecs"] = {anc = "", tga = ""}, ["Ujlak"] = {anc = "", tga = ""},
            ["Temesvar"] = {anc = "", tga = ""}, ["Varad"] = {anc = "", tga = ""},
            ["Debrecen"] = {anc = "", tga = ""}, ["Kassa"] = {anc = "", tga = ""},
            ["Beszterce"] = {anc = "", tga = ""}, ["Gyulafehervar"] = {anc = "", tga = ""},
            ["Fagaras"] = {anc = "", tga = ""}, ["Kronstadt"] = {anc = "", tga = ""},
            ["Severin"] = {anc = "", tga = ""}, ["Craiova"] = {anc = "", tga = ""},
            ["Arges"] = {anc = "", tga = ""}, ["Targoviste"] = {anc = "", tga = ""},
            ["Giurgiu"] = {anc = "", tga = ""}, ["Braila"] = {anc = "", tga = ""},
            ["Chilia"] = {anc = "", tga = ""}, ["Cetatea_Alba"] = {anc = "", tga = ""},
            ["Iasi"] = {anc = "", tga = ""}, ["Targu_Neamt"] = {anc = "", tga = ""},
            ["Suceava"] = {anc = "", tga = ""}, ["Hotin"] = {anc = "", tga = ""},
            ["Halicz"] = {anc = "", tga = ""}, ["Kamianets"] = {anc = "", tga = ""},
            ["Bratzlav"] = {anc = "", tga = ""}, ["Ozu-Cale"] = {anc = "", tga = ""},
            ["Oleski"] = {anc = "", tga = ""}, ["Qirim"] = {anc = "", tga = ""},
            ["Caffa"] = {anc = "", tga = ""}, ["Theodoro"] = {anc = "", tga = ""},
            ["Pola"] = {anc = "", tga = ""}, ["Udine"] = {anc = "", tga = ""},
            ["Treviso"] = {anc = "", tga = ""}, ["Venezia"] = {anc = "", tga = ""},
            ["Padova"] = {anc = "", tga = ""}, ["Verona"] = {anc = "", tga = ""},
            ["Brescia"] = {anc = "", tga = ""}, ["Como"] = {anc = "", tga = ""},
            ["Milan"] = {anc = "", tga = ""}, ["Asti"] = {anc = "", tga = ""},
            ["Genova"] = {anc = "", tga = ""}, ["Parma"] = {anc = "", tga = ""},
            ["Modena"] = {anc = "", tga = ""}, ["Ferrara"] = {anc = "", tga = ""},
            ["Ravenna"] = {anc = "", tga = ""}, ["Bologna"] = {anc = "", tga = ""},
            ["Firenze"] = {anc = "", tga = ""}, ["Lucca"] = {anc = "", tga = ""},
            ["Pisa"] = {anc = "", tga = ""}, ["Siena"] = {anc = "", tga = ""},
            ["Arezzo"] = {anc = "", tga = ""}, ["Urbino"] = {anc = "", tga = ""},
            ["Ancona"] = {anc = "", tga = ""}, ["Perugia"] = {anc = "", tga = ""},
            ["Spoleto"] = {anc = "", tga = ""}, ["Rome_Province"] = {anc = "", tga = ""},
            ["Rome"] = {anc = "", tga = ""}, ["Aquila"] = {anc = "", tga = ""},
            ["Napoli"] = {anc = "", tga = ""}, ["Salerno"] = {anc = "", tga = ""},
            ["San_Severo"] = {anc = "", tga = ""}, ["Bari"] = {anc = "", tga = ""},
            ["Taranto"] = {anc = "", tga = ""}, ["Lecce"] = {anc = "", tga = ""},
            ["Potenza"] = {anc = "", tga = ""}, ["Cosenza"] = {anc = "", tga = ""},
            ["Gorz"] = {anc = "", tga = ""}, ["Laibach"] = {anc = "", tga = ""},
            ["Cilli"] = {anc = "", tga = ""}, ["Sankt_Veit"] = {anc = "", tga = ""},
            ["Gratz"] = {anc = "", tga = ""}, ["Wien"] = {anc = "", tga = ""},
            ["Linz"] = {anc = "", tga = ""}, ["Salzburg"] = {anc = "", tga = ""},
            ["Innsbruck"] = {anc = "", tga = ""}, ["Trient"] = {anc = "", tga = ""},
            ["Chur"] = {anc = "", tga = ""}, ["Zurich"] = {anc = "", tga = ""},
            ["Luzern"] = {anc = "", tga = ""}, ["Bern"] = {anc = "", tga = ""},
            ["Brunn"] = {anc = "", tga = ""}, ["Ceske_Budejovice"] = {anc = "", tga = ""},
            ["Straubing"] = {anc = "", tga = ""}, ["Munchen"] = {anc = "", tga = ""},
            ["Ingolstadt"] = {anc = "", tga = ""}, ["Augsburg"] = {anc = "", tga = ""},
            ["Konstanz"] = {anc = "", tga = ""}, ["Freiburg"] = {anc = "", tga = ""},
            ["Stuttgart"] = {anc = "", tga = ""}, ["Strassburg"] = {anc = "", tga = ""},
            ["Uskudar"] = {anc = "", tga = ""}, ["Iznikmid"] = {anc = "", tga = ""},
            ["Iznik"] = {anc = "", tga = ""}, ["Eskisehir"] = {anc = "", tga = ""},
            ["Bursa"] = {anc = "", tga = ""}, ["Balik_Hisar"] = {anc = "", tga = ""},
            ["Pegai"] = {anc = "", tga = ""}, ["Bergama"] = {anc = "", tga = ""},
            ["Manisa"] = {anc = "", tga = ""}, ["Smyrna"] = {anc = "", tga = ""},
            ["Guzelhisar"] = {anc = "", tga = ""}, ["Milas"] = {anc = "", tga = ""},
            ["Beskaza"] = {anc = "", tga = ""}, ["Adalia"] = {anc = "", tga = ""},
            ["Alaiye"] = {anc = "", tga = ""}, ["Karaman"] = {anc = "", tga = ""},
            ["Philadelphia"] = {anc = "", tga = ""}, ["Ladik"] = {anc = "", tga = ""},
            ["Burdur"] = {anc = "", tga = ""}, ["Aksehir"] = {anc = "", tga = ""},
            ["Konya"] = {anc = "", tga = ""}, ["Usak"] = {anc = "", tga = ""},
            ["Kutahya"] = {anc = "", tga = ""}, ["Kara_Hissar"] = {anc = "", tga = ""},
            ["Angora"] = {anc = "", tga = ""}, ["Kangri"] = {anc = "", tga = ""},
            ["Bolu"] = {anc = "", tga = ""}, ["Amastri"] = {anc = "", tga = ""},
            ["Kastamonu"] = {anc = "", tga = ""}, ["Corfu"] = {anc = "", tga = ""},
            ["Candia"] = {anc = "", tga = ""}, ["Rhodes"] = {anc = "", tga = ""},
            ["Kos"] = {anc = "", tga = ""}, ["Nasso"] = {anc = "", tga = ""},
            ["Negroponte"] = {anc = "", tga = ""}, ["Chio"] = {anc = "", tga = ""},
            ["Mytilene"] = {anc = "", tga = ""}, ["Palaiokastro"] = {anc = "", tga = ""},
            ["Nicosie"] = {anc = "", tga = ""}, ["Messina"] = {anc = "", tga = ""},
            ["Palermo"] = {anc = "", tga = ""}, ["Siracusa"] = {anc = "", tga = ""},
            ["Cagliari"] = {anc = "", tga = ""}, ["Bonifacio"] = {anc = "", tga = ""}}, 
        
    ["croatia"] = {["Pozega"] = {anc = "", tga = ""}, ["Zagreb"] = {anc = "", tga = ""},
            ["Bihac"] = {anc = "", tga = ""}, ["Knin"] = {anc = "", tga = ""},
            ["Zadar"] = {anc = "", tga = ""}, ["Split"] = {anc = "", tga = ""},
            ["Ston"] = {anc = "", tga = ""}, ["Ragusa"] = {anc = "", tga = ""},
            ["Blagaj"] = {anc = "", tga = ""}, ["Jajce"] = {anc = "", tga = ""},
            ["Doboj"] = {anc = "", tga = ""}, ["Srebrenik"] = {anc = "", tga = ""},
            ["Bobovac"] = {anc = "", tga = ""}, ["Kotor"] = {anc = "", tga = ""},
            ["Skadar"] = {anc = "", tga = ""}, ["Uzice"] = {anc = "", tga = ""},
            ["Ras"] = {anc = "", tga = ""}, ["Prizren"] = {anc = "", tga = ""},
            ["Novo_Brdo"] = {anc = "", tga = ""}, ["Nis"] = {anc = "", tga = ""},
            ["Skopje"] = {anc = "", tga = ""}, ["Ohrid"] = {anc = "", tga = ""},
            ["Prilep"] = {anc = "", tga = ""}, ["Stip"] = {anc = "", tga = ""},
            ["Rudnik"] = {anc = "", tga = ""}, ["Branicevo"] = {anc = "", tga = ""},
            ["Nandorfehervar"] = {anc = "", tga = ""}, ["Bdin"] = {anc = "", tga = ""},
            ["Sredets"] = {anc = "", tga = ""}, ["Tsepina"] = {anc = "", tga = ""},
            ["Plovdiv"] = {anc = "", tga = ""}, ["Lovets"] = {anc = "", tga = ""},
            ["Nikopol"] = {anc = "", tga = ""}, ["Tarnovo"] = {anc = "", tga = ""},
            ["Drastar"] = {anc = "", tga = ""}, ["Karvuna"] = {anc = "", tga = ""},
            ["Varna"] = {anc = "", tga = ""}, ["Nesebar"] = {anc = "", tga = ""},
            ["Galata"] = {anc = "", tga = ""}, ["Constantinople"] = {anc = "", tga = ""},
            ["Raidestos"] = {anc = "", tga = ""}, ["Kallipolis"] = {anc = "", tga = ""},
            ["Didymoteichon"] = {anc = "", tga = ""}, ["Adrianople"] = {anc = "", tga = ""},
            ["Christoupolis"] = {anc = "", tga = ""}, ["Serrai"] = {anc = "", tga = ""},
            ["Salonica"] = {anc = "", tga = ""}, ["Berroia"] = {anc = "", tga = ""},
            ["Kastoria"] = {anc = "", tga = ""}, ["Kruje"] = {anc = "", tga = ""},
            ["Durazzo"] = {anc = "", tga = ""}, ["Valona"] = {anc = "", tga = ""},
            ["Ioannina"] = {anc = "", tga = ""}, ["Lepanto"] = {anc = "", tga = ""},
            ["Larissa"] = {anc = "", tga = ""}, ["Neopatria"] = {anc = "", tga = ""},
            ["Athens"] = {anc = "", tga = ""}, ["Corinth"] = {anc = "", tga = ""},
            ["Patras"] = {anc = "", tga = ""}, ["Andreville"] = {anc = "", tga = ""},
            ["Modon"] = {anc = "", tga = ""}, ["Mystras"] = {anc = "", tga = ""},
            ["Buda"] = {anc = "", tga = ""}, ["Pest"] = {anc = "", tga = ""},
            ["Pozsony"] = {anc = "", tga = ""}, ["Veszprem"] = {anc = "", tga = ""},
            ["Pecs"] = {anc = "", tga = ""}, ["Ujlak"] = {anc = "", tga = ""},
            ["Temesvar"] = {anc = "", tga = ""}, ["Varad"] = {anc = "", tga = ""},
            ["Debrecen"] = {anc = "", tga = ""}, ["Kassa"] = {anc = "", tga = ""},
            ["Beszterce"] = {anc = "", tga = ""}, ["Gyulafehervar"] = {anc = "", tga = ""},
            ["Fagaras"] = {anc = "", tga = ""}, ["Kronstadt"] = {anc = "", tga = ""},
            ["Severin"] = {anc = "", tga = ""}, ["Craiova"] = {anc = "", tga = ""},
            ["Arges"] = {anc = "", tga = ""}, ["Targoviste"] = {anc = "", tga = ""},
            ["Giurgiu"] = {anc = "", tga = ""}, ["Braila"] = {anc = "", tga = ""},
            ["Chilia"] = {anc = "", tga = ""}, ["Cetatea_Alba"] = {anc = "", tga = ""},
            ["Iasi"] = {anc = "", tga = ""}, ["Targu_Neamt"] = {anc = "", tga = ""},
            ["Suceava"] = {anc = "", tga = ""}, ["Hotin"] = {anc = "", tga = ""},
            ["Halicz"] = {anc = "", tga = ""}, ["Kamianets"] = {anc = "", tga = ""},
            ["Bratzlav"] = {anc = "", tga = ""}, ["Ozu-Cale"] = {anc = "", tga = ""},
            ["Oleski"] = {anc = "", tga = ""}, ["Qirim"] = {anc = "", tga = ""},
            ["Caffa"] = {anc = "", tga = ""}, ["Theodoro"] = {anc = "", tga = ""},
            ["Pola"] = {anc = "", tga = ""}, ["Udine"] = {anc = "", tga = ""},
            ["Treviso"] = {anc = "", tga = ""}, ["Venezia"] = {anc = "", tga = ""},
            ["Padova"] = {anc = "", tga = ""}, ["Verona"] = {anc = "", tga = ""},
            ["Brescia"] = {anc = "", tga = ""}, ["Como"] = {anc = "", tga = ""},
            ["Milan"] = {anc = "", tga = ""}, ["Asti"] = {anc = "", tga = ""},
            ["Genova"] = {anc = "", tga = ""}, ["Parma"] = {anc = "", tga = ""},
            ["Modena"] = {anc = "", tga = ""}, ["Ferrara"] = {anc = "", tga = ""},
            ["Ravenna"] = {anc = "", tga = ""}, ["Bologna"] = {anc = "", tga = ""},
            ["Firenze"] = {anc = "", tga = ""}, ["Lucca"] = {anc = "", tga = ""},
            ["Pisa"] = {anc = "", tga = ""}, ["Siena"] = {anc = "", tga = ""},
            ["Arezzo"] = {anc = "", tga = ""}, ["Urbino"] = {anc = "", tga = ""},
            ["Ancona"] = {anc = "", tga = ""}, ["Perugia"] = {anc = "", tga = ""},
            ["Spoleto"] = {anc = "", tga = ""}, ["Rome_Province"] = {anc = "", tga = ""},
            ["Rome"] = {anc = "", tga = ""}, ["Aquila"] = {anc = "", tga = ""},
            ["Napoli"] = {anc = "", tga = ""}, ["Salerno"] = {anc = "", tga = ""},
            ["San_Severo"] = {anc = "", tga = ""}, ["Bari"] = {anc = "", tga = ""},
            ["Taranto"] = {anc = "", tga = ""}, ["Lecce"] = {anc = "", tga = ""},
            ["Potenza"] = {anc = "", tga = ""}, ["Cosenza"] = {anc = "", tga = ""},
            ["Gorz"] = {anc = "", tga = ""}, ["Laibach"] = {anc = "", tga = ""},
            ["Cilli"] = {anc = "", tga = ""}, ["Sankt_Veit"] = {anc = "", tga = ""},
            ["Gratz"] = {anc = "", tga = ""}, ["Wien"] = {anc = "", tga = ""},
            ["Linz"] = {anc = "", tga = ""}, ["Salzburg"] = {anc = "", tga = ""},
            ["Innsbruck"] = {anc = "", tga = ""}, ["Trient"] = {anc = "", tga = ""},
            ["Chur"] = {anc = "", tga = ""}, ["Zurich"] = {anc = "", tga = ""},
            ["Luzern"] = {anc = "", tga = ""}, ["Bern"] = {anc = "", tga = ""},
            ["Brunn"] = {anc = "", tga = ""}, ["Ceske_Budejovice"] = {anc = "", tga = ""},
            ["Straubing"] = {anc = "", tga = ""}, ["Munchen"] = {anc = "", tga = ""},
            ["Ingolstadt"] = {anc = "", tga = ""}, ["Augsburg"] = {anc = "", tga = ""},
            ["Konstanz"] = {anc = "", tga = ""}, ["Freiburg"] = {anc = "", tga = ""},
            ["Stuttgart"] = {anc = "", tga = ""}, ["Strassburg"] = {anc = "", tga = ""},
            ["Uskudar"] = {anc = "", tga = ""}, ["Iznikmid"] = {anc = "", tga = ""},
            ["Iznik"] = {anc = "", tga = ""}, ["Eskisehir"] = {anc = "", tga = ""},
            ["Bursa"] = {anc = "", tga = ""}, ["Balik_Hisar"] = {anc = "", tga = ""},
            ["Pegai"] = {anc = "", tga = ""}, ["Bergama"] = {anc = "", tga = ""},
            ["Manisa"] = {anc = "", tga = ""}, ["Smyrna"] = {anc = "", tga = ""},
            ["Guzelhisar"] = {anc = "", tga = ""}, ["Milas"] = {anc = "", tga = ""},
            ["Beskaza"] = {anc = "", tga = ""}, ["Adalia"] = {anc = "", tga = ""},
            ["Alaiye"] = {anc = "", tga = ""}, ["Karaman"] = {anc = "", tga = ""},
            ["Philadelphia"] = {anc = "", tga = ""}, ["Ladik"] = {anc = "", tga = ""},
            ["Burdur"] = {anc = "", tga = ""}, ["Aksehir"] = {anc = "", tga = ""},
            ["Konya"] = {anc = "", tga = ""}, ["Usak"] = {anc = "", tga = ""},
            ["Kutahya"] = {anc = "", tga = ""}, ["Kara_Hissar"] = {anc = "", tga = ""},
            ["Angora"] = {anc = "", tga = ""}, ["Kangri"] = {anc = "", tga = ""},
            ["Bolu"] = {anc = "", tga = ""}, ["Amastri"] = {anc = "", tga = ""},
            ["Kastamonu"] = {anc = "", tga = ""}, ["Corfu"] = {anc = "", tga = ""},
            ["Candia"] = {anc = "", tga = ""}, ["Rhodes"] = {anc = "", tga = ""},
            ["Kos"] = {anc = "", tga = ""}, ["Nasso"] = {anc = "", tga = ""},
            ["Negroponte"] = {anc = "", tga = ""}, ["Chio"] = {anc = "", tga = ""},
            ["Mytilene"] = {anc = "", tga = ""}, ["Palaiokastro"] = {anc = "", tga = ""},
            ["Nicosie"] = {anc = "", tga = ""}, ["Messina"] = {anc = "", tga = ""},
            ["Palermo"] = {anc = "", tga = ""}, ["Siracusa"] = {anc = "", tga = ""},
            ["Cagliari"] = {anc = "", tga = ""}, ["Bonifacio"] = {anc = "", tga = ""}},

    ["bosnia"] = {},
    
    ["ragusa"] = {},
    
    ["serbia"] = {},
            ["albania"] = {},
            ["bulgaria"] = {},
            ["wallachia"] = {},
            ["moldova"] = {},
            ["tatars"] = {}
            ,["athens"] = {},
            ["rhodes"] = {},
            ["ottoman"] = {},
            ["aydin"] = {},
            ["karaman"] = {},
            ["venice"] = {},
            ["milan"] = {},
            ["genoa"] = {},
            ["florence"] = {},
            ["naples"] = {},
            ["trinacria"] = {},
            ["bohemia"] = {},
            ["austria"] = {},
            ["bavaria"] = {},
            ["switzerland"] = {}}
ancTable["kantakouzenos"] = ancTable["byzantium"]

	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
